### ISSUE TITLE
Links to background discussion

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/cwl-novice-tutorial#1]
Notes from the community call about this tutorial (2019-10-29): https://docs.google.com/document/d/1ciL2OE2bMitjaJSN6cJDRhrplHorN6QjPoaqzWnFIYM/edit

Original issue discussing this on User Guide repository: https://github.com/common-workflow-language/user_guide/issues/160

And a tweet on the topic: https://twitter.com/tbyhdgs/status/1162372570311745538

**Comment by stain** [comment]
Some slides introducing workflows and then CWL:
http://slides.com/soilandreyes/2019-09-18-cwl-cruk#/
