### ISSUE TITLE
Ep03: Multi-step workflow doesn't extend previous example

### ISSUE THREAD

**Issue by gcapes** [carpentries-incubator/cwl-novice-tutorial#101]
I think it did previously, but now the inputs and steps are renamed, so while the functionality remains, as a learner it feels like you're writing a whole new file rather than building on the previous episode.

**Comment by gcapes** [comment]
This text doesn't correspond to the example given
> The workflow file shows the first 3 steps of the RNA-seq analysis: quality_control, mapping_reads and index_alignment. The index_alignment step uses the alignment output of the mapping_reads step. You do this by referencing the output of the mapping_reads step in the in field of the index_alignment step. This is similar to referencing the outputs of the different steps in the outputs section.

The workflow file shown has the following steps: quality_control_forward, quality_control_reverse, trim_low_quality_bases and mapping_reads. 

Also, per my original comment, it very much looks like 4 new steps rather than mapping_reads being the only new step. The two quality control steps might be similar to the first one, but with different names it's not really a continuation of the previous episode.
> The newly added mapping_reads step also need an input not provided by any of our other steps,

**Comment by mr-c** [comment]
Fixed in https://github.com/carpentries-incubator/cwl-novice-tutorial/commit/9adab86c39df12c33c87e822494eefd83431d895 (my mistake for pushing directly without a code review; sorry!)

**Comment by gcapes** [comment]
https://github.com/carpentries-incubator/cwl-novice-tutorial/commit/9adab86c39df12c33c87e822494eefd83431d895 looks to fix #105 instead.

**Comment by mr-c** [comment]
Fixed in #118
