### ISSUE TITLE
Add setup info

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/cwl-novice-tutorial#11]
Once we have some exercises (#7), we should add some instructions to `setup.md` to guide learners through what they will need to install/connect to, to follow the tutorial.

**Comment by ALuesink** [comment]
Setup instructions are added in PR https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/50

**Comment by mr-c** [comment]
Thanks @ALuesink !
