### ISSUE TITLE
Why does title say "For Contributors"

### ISSUE THREAD

**Issue by swzCuroverse** [carpentries-incubator/cwl-novice-tutorial#125]
I am confused why the tile says -- "For Contributors" at the end of it.

**Comment by mr-c** [comment]
Which title? Can you share the URL of the page you're looking at?

**Comment by mr-c** [comment]
Ah, at https://carpentries-incubator.github.io/cwl-novice-tutorial/

**Comment by swzCuroverse** [comment]
I can't figure out where it is coming from in the code or I would fix it.

**Comment by mr-c** [comment]
Here's a fix: https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/126

**Comment by mr-c** [comment]
Fixed; thank you @swzCuroverse !
