### ISSUE TITLE
ERROR: Permission to common-workflow-lab/cwl-novice-tutorial.git denied

### ISSUE THREAD

**Issue by skanwal** [carpentries-incubator/cwl-novice-tutorial#15]
Hello @mr-c @tobyhodges @swzcuroverse

Just gearing up on this and facing an issue while trying to push a branch to this repo.

Tracing my own steps below:

```
$ git clone git@github.com:common-workflow-lab/cwl-novice-tutorial.git
$ git checkout -b script-sk
Switched to a new branch 'script-sk'
$ git push -u origin script-sk
ERROR: Permission to common-workflow-lab/cwl-novice-tutorial.git denied to skanwal.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have also tried cloning via https link but that gives `fatal: Authentication failed for 'https://github.com/common-workflow-lab/cwl-novice-tutorial.git/'`

Do I need to be added to repository or go through authentication?
Any help will be appreciated.

Best, 
Sehrish

**Comment by mr-c** [comment]
Hello Sehrish!

You'll need to accept the invitation at https://github.com/common-workflow-lab/cwl-novice-tutorial/invitations to be able to push here. Hope this fixes the problem for you :-)

**Comment by skanwal** [comment]
Thanks, Michael.

It seems the invitation has expired.. Can I please get it again? I didn't receive any email notification last time, hence probably missed it earlier..

**Comment by mr-c** [comment]
I resent it!

**Comment by skanwal** [comment]
Received and accepted.
Thank you.
