### ISSUE TITLE
Kick-off discussion

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/cwl-novice-tutorial#2]
Virtual kick off event on 2020-03-26, sign up at : https://bio-it.embl.de/events/lesson-development-sprint-common-workflow-language-tutorial/

--- Original message below for posterity --

We should try to meet together online some time soon, so we can figure out how to get started on this. Perhaps @fpsom and I can provide an overview of how to work with the Carpentries lesson template, and we can begin to agree on what the main concepts are that we'd like to cover in the tutorial. 

From there, in the following discussions we can start working out the relationships between these concepts and subsequently the order & content of the teaching material.

How does 22 November 15:30 UTC work for everyone? https://www.timeanddate.com/worldclock/fixedtime.html?msg=CWL+Tutorial+kick-off+call&iso=20191122T1530&p1=1440&ah=1

**Comment by fpsom** [comment]
Hi @tobyhodges - excellent idea!

Regarding the time, I'll be literally boarding a plane at that time on the way back from the ELIXIR BioHackathon, so I won't be able to join (the latest I could do on the 22nd would be at ~11:00 UTC, but I assume that would be too constrained for people outside EU).

That being said, I'm fairly certain that there will be a lot of discussions to follow that call, so if the day/time is convenient for a sufficient number of interested parties, let's keep it.

**Comment by mr-c** [comment]
I'll also be leaving the ELIXIR BioHackathon that afternoon, but luckily not by plane, so that time works for me. Thank you @tobyhodges for organzing this kickoff call!

**Comment by stain** [comment]
Sorry, time works poorly for me as I will also be on my way back from BioHackathon. Pinging @longr in case he can make it.

**Comment by ttubb** [comment]
There is some travel-related uncertainty, but i will most likely be able to attend.

**Comment by tobyhodges** [comment]
At the moment, I think it would be better to find a different time & date - it's important that as many as possible of our contributors can attend. 

Is anyone else reading this and would be able to attend at 15:30 UTC on Friday (22 November)?

Spoilers: one thing I intend to propose is that we should try to find an opportunity for several of us to meet in person to discuss this. The early stages of lesson design are much easier to do when we can easily see each other's pen and paper :)

**Comment by ttubb** [comment]
Will the discussion take place today?
It looks like i will be sitting in a car (as the passenger) at 15:30 UTC, so not ideal, but i would be able to join using my phone & headset.

**Comment by mr-c** [comment]
@tobyhodges I can join today, yes. It would be nice if we could choose a time when @fpsom @stain are available.

**Comment by tobyhodges** [comment]
Agreed. I'm travelling most of next week. How's Monday 2 December for everyone? To get the ball rolling, I propose 11:00 CET (10:00 UTC) https://www.timeanddate.com/worldclock/fixedtime.html?msg=CWL+Tutorial+Planning&iso=20191202T10&p1=%3A&ah=1

**Comment by ttubb** [comment]
Monday the 2nd works for me.

**Comment by fpsom** [comment]
Hi all. Monday the 2nd works for me - ideally at 10:00 CET or 12:00 CET (I have another call at 11:00 that I could change if really necessary / not another option available)

**Comment by fpsom** [comment]
Hi all! Given that there has been little on this thread so far, I do expect that the answer will be "no" but I will still ask; is today's call/meet still on? :)

**Comment by tobyhodges** [comment]
I am up for it if you are 🙂

**Comment by fpsom** [comment]
Cool! I'm in! Still at 11:00 CET? Also, what will we be using?

**Comment by tobyhodges** [comment]
We can meet on Zoom at https://zoom.us/j/535836763

**Comment by tobyhodges** [comment]
The notes from today's kickoff meeting are here: https://docs.google.com/document/d/12kUlKrrMZGou3VCy46Fqu8hIhq8HlHbwlySTmGNrh5o/edit#

Main outcomes were:

- target audience:
  - Knows how to run (bioinformatics) tools a command line
  - May be familiar with basics of piping/scripting
  - Needs to scale up their analysis
- central example should be simple but realistic e.g. variant calling pipeline (ELIXIR-relevant)
- we should focus the tutorial on a text-based interface, probably writing workflows in VSCode (to take advantage of syntax highlighting and plugins relevant to CWL), teaching CWL v1.1
- we'll hold a **lesson development meeting at EMBL Heidelberg on Thursday 26 March 2020** to try to get the bulk of the lesson design sorted. More info, including a registration link to follow.

**Comment by ttubb** [comment]
Hello everyone,

i don't know if this discussion has been continued since we talked in December (unfortunately I'm unable to attend the regular user meetings at the moment).
When we held the discussion in December i wasn't sure about the meetup on Thu, 26 March. Everything is sorted out now and i will be able to attend. Another member of the group i now work in has also expressed interest (Christian Henke, i think Michael has met him at a CWL-workshop already).

During the video call we also discussed searching BioStars to gather some information on the problems people are facing. Has anybody found time to start with this? If not, i will create a docs table and start to collect (and maybe somehow categorize) issues.

Cheers,
Tom

**Comment by tobyhodges** [comment]
This is great news, Tom. Please register here to help us plan numbers, communicate details closer to the time etc: https://bio-it.embl.de/events/lesson-development-sprint-common-workflow-language-tutorial/

**Comment by stain** [comment]
Hi, I guess reminder for people about the [tutorial development meetup](https://bio-it.embl.de/events/lesson-development-sprint-common-workflow-language-tutorial/) next month `2020-03-26` in Heidelberg. It looks like I won't be able to go because of other travel commitments, but if possible could I try to remote in?

**Comment by ttubb** [comment]
Hello fellow pipeline enthusiasts,
Because of the coronavirus outbreak our university has instructed employees to cancel trips unless "urgently required". So it looks like i will not be allowed to attend the lesson development sprint in Heidelberg. I was very much looking forward to the meeting. Hope the rest of you are having less trouble (and manage to stay healthy).
Regards,
Tom

**Comment by matuskalas** [comment]
Hey all, this sounds good! After an invite from @mr-c, I'm in :-)

**Comment by hmenager** [comment]
Depending on wether my agenda clears up for that day (highly likely given current situation) I'll be happy to join.

**Comment by tobyhodges** [comment]
Hey all, great to have you onboard for this **now entirely virtual** development sprint. Please register here to receive further updates, connection details, etc: https://bio-it.embl.de/events/lesson-development-sprint-common-workflow-language-tutorial/

**Comment by matuskalas** [comment]
Unfortunately I haven't been able to join you today @tobyhodges @mr-c 😿
Have a great productive day! I'm excited looking forward to checking out the results 🤩

**Comment by tobyhodges** [comment]
I'll report out from the lesson development sprint tomorrow, 21 April 2020, in the standard 14:30 UTC CWL community call timeslot and also earlier in the day at 07:00 UTC. I'm looking forward to giving you all an update on the progress we made and my suggestions for next steps to take.
