### ISSUE TITLE
Preview rendered website in pull requests

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/cwl-novice-tutorial#25]
During the lesson hackaton there was some interest in having previews of the website directly on pull requests before they are merged.

A few options were mentioned and pinned to be explored at a later point:

* [Surge.sh](https://github.com/marketplace/actions/surge-pr-preview)
* [Netlify](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)

**Comment by tobyhodges** [comment]
Others have enabled Netlify previews for Pull Requests on their lesson repository. Linking an example here in case it serves as a useful reference: https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/80

**Comment by mr-c** [comment]
Magic steps

1. Go to https://app.netlify.com/sites/agitated-wright-f1741d/settings/deploys#outgoing-notifications
2. "add notification" → "GitHub Pull Request comment"
3. "Event to listen for" → "Deploy Preview succeeded"
4. Results in "Add Deploy Preview notifications as pull request comments when Deploy Preview succeeds"

**Comment by mr-c** [comment]
@tobyhodges we lost this in the migration ; can you enable them here?

**Comment by MCMaurer** [comment]
@mr-c since Toby is on leave right now, I'm taking over his duties with the Carpentries Incubator. Happy to help get this working for you, but I'm not entirely sure what's needed to re-enable the Netlify app. If you can let me know what the necessary steps are, I'm happy to give it a go!

**Comment by mr-c** [comment]
@MCMaurer Thanks! From https://app.netlify.com/start please add https://github.com/carpentries-incubator/cwl-novice-tutorial then follow the instructions at https://github.com/carpentries-incubator/cwl-novice-tutorial/issues/25#issuecomment-804799417 using the new URL netlify gives you

**Comment by MCMaurer** [comment]
@mr-c alright, I think I got it done. It's currently running on my personal Netlify account, I'm going to try to figure out what the policy is for putting Incubator lessons on the org's Netlify. I'll get back to you once I've got that figured out!

**Comment by mr-c** [comment]
@MCMaurer I deleted my netlify site `cwl-novice-tutorial` from the old repo location if you want to rename `thirsty-hoover-1e0704` to that :-)

**Comment by MCMaurer** [comment]
Hey @mr-c, just getting around to this now! I just saw this as well as the PR you tagged me in. 

I actually put up this Netlify app with my personal account, and it looks like there's no way to transfer the project to our Carpentries account. I'm going to go ahead and have another Core Team member do the same steps with that account, and I'll let you know here as soon as I do! Does that sound alright to you?

**Comment by mr-c** [comment]
@MCMaurer that works for me!
