### ISSUE TITLE
Write & test setup instructions

### ISSUE THREAD

**Issue by mr-c** [carpentries-incubator/cwl-novice-tutorial#39]
Write up MS VS Code instructions, and test them.
For MS Windows users, this means setting up Docker + WSL 2, and other components

https://github.com/common-workflow-language/cwltool#ms-windows-users

**Comment by mr-c** [comment]
and Benten ( + cwltool, if Benten doesn't pull that in automatically)

**Comment by mr-c** [comment]
Must use virtualenv to get newer cwltool version than is in Debian stable so that `--print-dot` works with spaces in identifiers

**Comment by ALuesink** [comment]
The use of a virtual environment is added to the setup instruction in PR https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/55/
