### ISSUE TITLE
enable @mr-c permissions to merge https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/44

### ISSUE THREAD

**Issue by mr-c** [carpentries-incubator/cwl-novice-tutorial#48]

**Comment by mr-c** [comment]
Ping @MCMaurer

**Comment by MCMaurer** [comment]
Hey @mr-c, just checking on this- do you not have permissions to merge this PR with Maintain access? If not, I can make you an Admin on the repo.

**Comment by mr-c** [comment]
> Hey @mr-c, just checking on this- do you not have permissions to merge this PR with Maintain access? If not, I can make you an Admin on the repo.

Admin access would ve appreciated, thanks

**Comment by mr-c** [comment]
@MCMaurer Yeah, looks like I need admin access to approve GitHub Action workflow running for first time contributors? https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/49

In this case I fixed it by force-pushing to the contributors branch with a commit from me, but this will not always be possible

**Comment by MCMaurer** [comment]
@mr-c got it, just gave you Admin access!
