### ISSUE TITLE
Is index in addition to rnaseq files?

### ISSUE THREAD

**Issue by gcapes** [carpentries-incubator/cwl-novice-tutorial#99]
The setup section asks learners to download 'sample and reference data', and then talks about generating an index from the downloaded data. For those without 9GB ram spare, it suggests downloading the index instead of creating it using the STAR aligner tool. Does this mean that learners in this situation would not need to download the sample and reference data?

**Comment by mr-c** [comment]
Good point, we could clarify that everyone needs 1) 1st set of subsampled reads and 2) the gene model, and then they either need to download the indexed genome OR download the un-indexed reference genome and index it themselves.
